<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>


<section class="dashboard-page">
	<div class="container-fluid">
		<div class="title-wrapper pt-30">
			<div class="row align-items-center">
				<div class="col-lg-6 col-md-6 col-sm-12 col-12">
					<div class="title mb-30">
						<h2>Faculty Details Upload Guide</h2>
					</div>
				</div>
				<!-- end col -->
				<div class="col-lg-6 col-md-6 col-sm-12 col-12">
					<div class="breadcrumb-wrapper mb-30">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="nch_inst_helptopics">Help Topics</a></li>
								<li class="breadcrumb-item active" aria-current="page">Faculty Details Upload Guide</li>
							</ol>
						</nav>
					</div>
				</div>
				<!-- end col -->
			</div>
			<!-- end row -->
		</div>

		<div class="form-elements-wrapper">
			<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-12">
				<div class="card-style mb-30 guide_block">
					<div class="counter-section">

						<h5 class="section-title">Overview</h5>

						<p>As part of Faculty process filling the details of faculty in the AYUSH Education Portal. This service enables to faculty to fill the form of all the faculty details after <b>Sign In</b> to the portal.</p>

						<h5 class="section-title">Step-by-Step Guide</h5>
						<p class="custom-step">
							<span class="custom-step-title">STEP 1: </span>Institute will be redirected to Dashboard after login where Faculty can select options available in Menu as per need.
						</p>

						<div class="custom-stepimg">
							<img
								src="assets/img/module_guide_img/nch/institute/nch-institute-1.png"
								alt="nch-institute-1" title="nch-institute-1"
								class="img-fluid">
						</div>


						<p class="custom-step">
							<span class="custom-step-title">STEP 2: </span>These process of step is mandatory for <b>Institute</b> level before accessing the Faculty Module. Particular institute needs to upload the details of faculty. we are going to familiarize ourselves with the process of <b>FACULTY DETAILS</b>.
						</p>
						<p class="custom-step">
							
						Within the process, Institute has to select <span class="text-heighlight">FACULTY DETAILS  >  FACULTY FORM > Faculty Excel Upload</span> from menu.
							
						</p>

						<div class="custom-stepimg">
							<img
								src="assets/img/module_guide_img/nch/institute/nch-institute-2.png"
								alt="nch-institute-2" title="nch-institute-2"
								class="img-fluid">
						</div>


						<p class="custom-step">
							<span class="custom-step-title">STEP 3: </span>Firstly, it is necessary to download an Excel sheet by clicking the <b>Export Sample Template Format</b> button. The faculty's login will be generated by filling in the required details in this sheet.
						</p>
						
							<div class="custom-stepimg">
								<img
									src="assets/img/module_guide_img/nch/institute/nch-institute-3.png"
									alt="nch-institute-3" title="nch-institute-3" class="img-fluid">
							</div>

							<p class="custom-step">
							<span class="custom-step-title">STEP 4: </span>The process requires you to save the Excel sheet and subsequently upload it in the designated <b>Upload File</b> field.
						</p>
						
						<div class="custom-stepimg">
								<img
									src="assets/img/module_guide_img/nch/institute/nch-institute-4.png"
									alt="nch-institute-4" title="nch-institute-4" class="img-fluid">
							</div>
						
							<p class="custom-step">
							<span class="custom-step-title">STEP 5: </span>You are now required to click on the <b>Save</b> button. In case you need to reset the details, you can also click on the <b>Reset</b> button.
						</p>



						<div class="custom-stepimg">
								<img
									src="assets/img/module_guide_img/nch/institute/nch-institute-5.png"
									alt="nch-institute-5" title="nch-institute-5" class="img-fluid">
							</div>
						
						<p class="custom-step">
							<span class="custom-step-title">STEP 6: </span>Registration Mail has been sent to all Uploaded Faculty. Now, Faculty can access Portal.
						</p>
                        
                        <p><b>Thank you!</b> Hopefully this guidence useful for explor and easy to use the Ayush Education Portal.</p>
						
					</div>

				</div>
			</div>

		</div>
		</div>
	</div>
</section>

