package com.AyushEdu.config;


public class MailHTMLNCISM {
private String HTML;

public String getHTML() {
	return HTML;
}

public void setHTML(String role ,String before,String after) {
	String main = before;
//	String op = otp;
	String followup = after;
	
	
	
	HTML =  "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Ayush Grid Email Template</title>\r\n"
			+ "    <link href=\"https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Montserrat:wght@100;400;500;600&display=swap\" rel=\"stylesheet\">\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body style=\"margin: 0;\">\r\n"
			+ "    <div style=\"background-color:#e6f3ff;margin:0;padding:0\">\r\n"
			+ "        <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#e6f3ff; font-family: 'Montserrat', sans-serif;font-weight:400;\">\r\n"
			+ "          <tbody>\r\n"
			+ "            <tr>\r\n"
			+ "              <td>\r\n"
			+ "                <!-- email header start -->\r\n"
			+ "                <table align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-position:center top\">\r\n"
			+ "                  <tbody>\r\n"
			+ "                    <tr>\r\n"
			+ "                      <td>\r\n"
			+ "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"color:#000;width:650\" width=\"650\">\r\n"
			+ "                          <tbody>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td width=\"100%\" style=\"text-align:left;vertical-align:top;padding-left:15px;padding-right:15px;padding-top:0;padding-bottom:0;border-top:0;border-right:0;border-bottom:0;border-left:0\">\r\n"
			+ "                                <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
			+ "                                  <tbody>\r\n"
			+ "                                    <tr>\r\n"
			+ "                                      <td style=\"width:100%;padding-right:0;padding-left:0;padding-top:30px\">\r\n"
			+ "                                        <div align=\"center\" style=\"line-height:10px\">\r\n"
			+ "                                          <a href=\"#\"><img src=\"cid:logo1\" style=\"display:block;height:auto;border:0;width:90px;max-width:100%;background: rgba(255,255,255,0.5); \r\n"
			+ "                                          padding: 2px\" width=\"90\" tabindex=\"0\" title=\"ncism-logo\"></a>\r\n"
			+ "                                        </div>\r\n"
			+ "                                      </td>\r\n"
			+ "                                    </tr>\r\n"
			+ "                                    <tr>\r\n"
			+ "                                        <td>\r\n"
			+ "                                          <div style=\"color:#454562;direction:ltr;font-size:20px;font-weight:500;letter-spacing:0;line-height:120%;text-align:center;padding-top:15px\">\r\n"
			+ "                                            <p style=\"margin:0\">\r\n"
			+ "                                              Hello&nbsp;<strong style=\"color:#014a91;\">"+role+" , </strong>Nice to meet you!\r\n"
			+ "                                            </p>\r\n"
			+ "                                          </div>\r\n"
			+ "                                        </td>\r\n"
			+ "                                      </tr>\r\n"
			+ "                                  </tbody>\r\n"
			+ "                                </table>\r\n"
			+ "                                <div style=\"height:30px;line-height:30px\"></div>\r\n"
			+ "                              </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                          </tbody>\r\n"
			+ "                        </table>\r\n"
			+ "                      </td>\r\n"
			+ "                    </tr>\r\n"
			+ "                  </tbody>\r\n"
			+ "                </table>\r\n"
			+ "                <!-- email header end -->\r\n"
			+ "\r\n"
			+ "                <!-- email body start -->\r\n"
			+ "                <table align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td><table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#d3ffe4;color:#222222;border-radius:15px 15px 0 0;width:650\" width=\"650\"><tbody><tr><td width=\"100%\" style=\"font-weight:400;text-align:left;vertical-align:top;padding-top:0px;padding-bottom:0px;border-top:0px;border-right:0px;border-bottom:0px;border-left:0px\"><div style=\"height:20px;line-height:20px\"></div></td></tr></tbody></table></td></tr></tbody></table>\r\n"
			+ "               \r\n"
			+ "                <table align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#cbe5ff\">\r\n"
			+ "                  <tbody>\r\n"
			+ "                    <tr>\r\n"
			+ "                      <td>\r\n"
			+ "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#fff;color:#000;width:650\" width=\"650\">\r\n"
			+ "                          <tbody>\r\n"
			+ "                            <tr>\r\n"
			+ "                                <td style=\"padding-bottom:20px;padding-left:30px;padding-right:30px;padding-top:5px;text-align:center;width:100%;background:#d3ffe4\">\r\n"
			+ "                                  <h1 style=\"margin:0;color:#014a91;direction:ltr;font-size:24px;font-weight:400;letter-spacing:normal;line-height:120%;text-align:center;margin-top:0;margin-bottom:0;\">\r\n"
			+ "                                    <strong>Welcome to NCISM - Ministry of Ayush!!</strong>\r\n"
			+ "                                  </h1>\r\n"
			+ "                                </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td style=\"padding-bottom:15px;padding-left:30px;padding-right:30px;padding-top:15px;border-bottom: 1px solid #e6e6e6;\">\r\n"
			+ "                                <div style=\"color:#454562;direction:ltr;font-size:18px;font-weight:500;letter-spacing:0;line-height:150%;text-align:center\">\r\n"
			+ "                                   "+main+"\r\n"
			+ "                                </div>\r\n"
			+ "                              </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td style=\"padding-bottom:15px;padding-left:30px;padding-right:30px;padding-top:15px;\">\r\n"
			+ "                                <div style=\"color:#454562;direction:ltr;font-size:16px;font-weight:400;letter-spacing:0.5px;line-height:180%;text-align:left\">\r\n"
			+ "                                  "+followup+"\r\n"
			+ "                                </div>\r\n"
			+ "                              </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td style=\"padding-bottom:30px;padding-left:10px;padding-right:10px;padding-top:10px;text-align:center\"><div align=\"center\">\r\n"
			+ "                              <a href=\"https://apps.bisag.co.in/BISAG/landingpage\" style=\"text-decoration:none;display:inline-block;color:#014a91;background-color:transparent;border-radius:50px;width:auto;border-top:2px solid #014a91;border-right:2px solid #014a91;border-bottom:2px solid #014a91;border-left:2px solid #014a91;padding-top:5px;padding-bottom:5px;text-align:center;word-break:keep-all\" target=\"_blank\"><span style=\"padding-left:35px;padding-right:35px;font-size:18px;display:inline-block;letter-spacing:normal\"><span style=\"font-size:16px;line-height:2;word-break:break-word\"><span style=\"font-size:15px;line-height:36px;font-weight:600\">Explore Ayush EDU More</span></span></span></a>\r\n"
			+ "                              </div>\r\n"
			+ "                              </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                          </tbody>\r\n"
			+ "                        </table>\r\n"
			+ "                      </td>\r\n"
			+ "                    </tr>\r\n"
			+ "                  </tbody>\r\n"
			+ "                </table>\r\n"
			+ "                <!-- email body end -->\r\n"
			+ "\r\n"
			+ "                <!-- email img start -->\r\n"
			+ "                <table align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
			+ "                  <tbody>\r\n"
			+ "                    <tr>\r\n"
			+ "                      <td>\r\n"
			+ "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"color:#000;width:650\" width=\"650\">\r\n"
			+ "                          <tbody>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td style=\"width:100%;padding-right:0;padding-left:0;padding-top:20px\">\r\n"
			+ "                                <div align=\"center\" style=\"line-height:10px\">\r\n"
			+ "                                  <img src=\"cid:logo2\" style=\"display:block;height:auto;border:0;width:250px;max-width:100%\" width=\"347\" alt=\"email image\" title=\"email image\" tabindex=\"0\">\r\n"
			+ "                                </div>\r\n"
			+ "                              </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                          </tbody>\r\n"
			+ "                        </table>\r\n"
			+ "                      </td>\r\n"
			+ "                    </tr>\r\n"
			+ "                  </tbody>\r\n"
			+ "                </table>\r\n"
			+ "                <!-- email img end -->\r\n"
			+ "\r\n"
			+ "                <!-- email footer start -->\r\n"
			+ "                <table align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#fff\">\r\n"
			+ "                  <tbody>\r\n"
			+ "                    <tr>\r\n"
			+ "                      <td>\r\n"
			+ "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#fff;color:#000;width:650\" width=\"650\">\r\n"
			+ "                          <tbody>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td width=\"100%\" style=\"font-weight:400;text-align:left;vertical-align:top;padding-left:20px;padding-right:20px;padding-top:20px;padding-bottom:20px;border-top:0;border-right:0;border-bottom:0;border-left:0\">\r\n"
			+ "                                <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
			+ "                                  <tbody>\r\n"
			+ "                                    <tr>\r\n"
			+ "                                      <td style=\"padding-bottom:5px;width:100%;padding-right:0;padding-left:0\">\r\n"
			+ "                                        <div align=\"center\" style=\"line-height:10px; text-align: center\">\r\n"
			+ "                                          <a href=\"https://main.ayush.gov.in/\" target=\"_blank\" >\r\n"
			+ "                                            <img src=\"cid:logo3\" style=\"display:block;height:auto;border:0;width:120px;max-width:100%;margin:auto\" width=\"120\" alt=\"ayush grid Logo\" title=\"ayush grid Logo\">\r\n"
			+ "                                          </a>\r\n"
			+ "                                        </div>\r\n"
			+ "                                      </td>\r\n"
			+ "                                    </tr>\r\n"
			+ "                                  </tbody>\r\n"
			+ "                                </table>\r\n"
			+ "                                <table width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" style=\"word-break:break-word\">\r\n"
			+ "                                  <tbody>\r\n"
			+ "                                    <tr>\r\n"
			+ "                                      <td>\r\n"
			+ "                                        <div style=\"font-family:sans-serif\">\r\n"
			+ "                                          <div style=\"font-size:12px;color:#454562;line-height:1.2\">\r\n"
			+ "                                            <p style=\"margin:auto;font-size:14px;text-align:center\">\r\n"
			+ "                                              <span style=\"font-size:16px\">\r\n"
			+ "                                                <strong>Connect with us on social media</strong>\r\n"
			+ "                                              </span>\r\n"
			+ "                                            </p>\r\n"
			+ "                                          </div>\r\n"
			+ "                                        </div>\r\n"
			+ "                                      </td>\r\n"
			+ "                                    </tr>\r\n"
			+ "                                  </tbody>\r\n"
			+ "                                </table>\r\n"
			+ "                                <table width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\">\r\n"
			+ "                                  <tbody>\r\n"
			+ "                                    <tr>\r\n"
			+ "                                      <td>\r\n"
			+ "                                        <table width=\"230px\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\r\n"
			+ "                                          <tbody>\r\n"
			+ "                                            <tr>\r\n"
			+ "                                              <td style=\"padding:0 7px 0 7px\">\r\n"
			+ "                                                <a href=\"https://www.facebook.com/moayush/\" target=\"_blank\" >\r\n"
			+ "                                                  <img src=\"cid:logo4\" width=\"32\" height=\"32\" alt=\"Facebook\" title=\"Facebook\" style=\"display:block;height:auto;border:0;margin: auto\">\r\n"
			+ "                                                </a>\r\n"
			+ "                                              </td>\r\n"
			+ "                                              <td style=\"padding:0 7px 0 7px\">\r\n"
			+ "                                                <a href=\"https://twitter.com/moayush\" target=\"_blank\" >\r\n"
			+ "                                                  <img src=\"cid:logo5\" width=\"32\" height=\"32\" alt=\"Twitter\" title=\"Twitter\" style=\"display:block;height:auto;border:0;margin: auto\">\r\n"
			+ "                                                </a>\r\n"
			+ "                                              </td>\r\n"
			+ "                                              <td style=\"padding:0 7px 0 7px\">\r\n"
			+ "                                                <a href=\"https://www.instagram.com/ministryofayush/\" target=\"_blank\">\r\n"
			+ "                                                  <img src=\"cid:logo6\" width=\"32\" height=\"32\" alt=\"Instagram\" title=\"Instagram\" style=\"display:block;height:auto;border:0;margin: auto\">\r\n"
			+ "                                                </a>\r\n"
			+ "                                              </td>\r\n"
			+ "                                            <!--   <td style=\"padding:0 7px 0 7px\">\r\n"
			+ "                                                <a href=\"#\">\r\n"
			+ "                                                  <img src=\"cid:logo7\" width=\"32\" height=\"32\" alt=\"Pinterest\" title=\"Pinterest\" style=\"display:block;height:auto;border:0;margin: auto\">\r\n"
			+ "                                                </a>\r\n"
			+ "                                              </td>\r\n"
			+ "                                              <td style=\"padding:0 7px 0 7px\">\r\n"
			+ "                                                <a href=\"#\">\r\n"
			+ "                                                  <img src=\"cid:logo8\" width=\"32\" height=\"32\" alt=\"LinkedIn\" title=\"LinkedIn\" style=\"display:block;height:auto;border:0;margin: auto\">\r\n"
			+ "                                                </a>\r\n"
			+ "                                              </td>\r\n"
			+ "                                              <td style=\"padding:0 7px 0 7px\">\r\n"
			+ "                                                <a href=\"#\">\r\n"
			+ "                                                  <img src=\"cid:logo9\" width=\"32\" height=\"32\" alt=\"whatsapp\" title=\"whatsapp\" style=\"display:block;height:auto;border:0;margin: auto\">\r\n"
			+ "                                                </a>\r\n"
			+ "                                              </td>  -->  \r\n"
			+ "                                            </tr>\r\n"
			+ "                                          </tbody>\r\n"
			+ "                                        </table>\r\n"
			+ "                                      </td>\r\n"
			+ "                                    </tr>\r\n"
			+ "                                  </tbody>\r\n"
			+ "                                </table>\r\n"
			+ "                                <table width=\"100%\" border=\"0\" cellpadding=\"15\" cellspacing=\"0\" style=\"word-break:break-word\">\r\n"
			+ "                                  <tbody>\r\n"
			+ "                                    <tr>\r\n"
			+ "                                      <td>\r\n"
			+ "                                        <div style=\"font-family:sans-serif\">\r\n"
			+ "                                          <div style=\"font-size:12px;color:#454562;line-height:1.5\">\r\n"
			+ "                                            <p style=\"margin:0;font-size:14px;text-align:center\">\r\n"
			+ "                                              <span>\r\n"
			+ "                                                <a style=\"text-decoration:underline;color:#454562\" href=\"tel:1800-11-0180,1964\">Contact: 1800-11-0180,1964</a> &nbsp;|&nbsp;\r\n"
			+ "                                                <a style=\"text-decoration:underline;color:#454562\" href=\"mailto:webmanager-ayush@gov.in\">Email Us: webmanager-ayush@gov.in</a>\r\n"
			+ "                                            </p>\r\n"
			+ "                                          </div>\r\n"
			+ "                                        </div>\r\n"
			+ "                                      </td>\r\n"
			+ "                                    </tr>\r\n"
			+ "                                  </tbody>\r\n"
			+ "                                </table>\r\n"
			+ "                                <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"word-break:break-word\">\r\n"
			+ "                                  <tbody>\r\n"
			+ "                                    <tr>\r\n"
			+ "                                      <td style=\"padding-left:10px;padding-right:10px;padding-top:10px\">\r\n"
			+ "                                        <div style=\"font-family:sans-serif\">\r\n"
			+ "                                          <div style=\"font-size:12px;color:#454562;line-height:1.5\">\r\n"
			+ "                                            <p style=\"margin:0;font-size:14px;text-align:center\">\r\n"
			+ "                                              <span style=\"font-size:13px\">This Portal is designed, developed and hosted by | <a href=\"https://bisag-n.gov.in/\" class=\"f-link\">BISAG-N</a> , Government of India.</span>\r\n"
			+ "                                            </p>\r\n"
			+ "                                          </div>\r\n"
			+ "                                        </div>\r\n"
			+ "                                      </td>\r\n"
			+ "                                    </tr>\r\n"
			+ "                                  </tbody>\r\n"
			+ "                                </table>\r\n"
			+ "                              </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                          </tbody>\r\n"
			+ "                        </table>\r\n"
			+ "                      </td>\r\n"
			+ "                    </tr>\r\n"
			+ "                  </tbody>\r\n"
			+ "                </table>\r\n"
			+ "                <!-- email footer end -->\r\n"
			+ "\r\n"
			+ "                <!-- email copyright start -->\r\n"
			+ "                <table align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#014a91\">\r\n"
			+ "                  <tbody>\r\n"
			+ "                    <tr>\r\n"
			+ "                      <td>\r\n"
			+ "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"color:#222222;width:650\" width=\"650\">\r\n"
			+ "                          <tbody>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td width=\"100%\" style=\"font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0\">\r\n"
			+ "                                <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
			+ "                                  <tbody>\r\n"
			+ "                                    <tr>\r\n"
			+ "                                      <td style=\"vertical-align:middle;color:#fff;font-family:inherit;font-size:15px;padding-bottom:5px;padding-top:5px;text-align:center\">\r\n"
			+ "                                        <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
			+ "                                          <tbody>\r\n"
			+ "                                            <tr>\r\n"
			+ "                                              <td style=\"vertical-align:middle;text-align:center\">\r\n"
			+ "                                                <table style=\"display:inline-block;padding-left:0;padding-right:0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
			+ "                                                  <tbody>\r\n"
			+ "                                                    <tr>\r\n"
			+ "                                                      <td style=\"vertical-align:middle;text-align:center;padding-top:5px;padding-bottom:5px;padding-left:5px;padding-right:6px\">\r\n"
			+ "                                                        <a href=\"#\">\r\n"
			+ "                                                          <img alt=\"Designed with BEE\" src=\"cid:logo10\" height=\"16\" width=\"16\" align=\"center\" style=\"display:block;height:auto;margin:auto;border:0\">\r\n"
			+ "                                                        </a>\r\n"
			+ "                                                      </td>\r\n"
			+ "                                                      <td style=\"font-size:15px;color:#fff;vertical-align:middle;letter-spacing:undefined;text-align:center\">\r\n"
			+ "                                                        <p href=\"#\">&#169; 2023 Ministry of Ayush. Government of India, All rights reserved.</p>\r\n"
			+ "                                                      </td>\r\n"
			+ "                                                    </tr>\r\n"
			+ "                                                  </tbody>\r\n"
			+ "                                                </table>\r\n"
			+ "                                              </td>\r\n"
			+ "                                            </tr>\r\n"
			+ "                                          </tbody>\r\n"
			+ "                                        </table>\r\n"
			+ "                                      </td>\r\n"
			+ "                                    </tr>\r\n"
			+ "                                  </tbody>\r\n"
			+ "                                </table>\r\n"
			+ "                              </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                          </tbody>\r\n"
			+ "                        </table>\r\n"
			+ "                      </td>\r\n"
			+ "                    </tr>\r\n"
			+ "                  </tbody>\r\n"
			+ "                </table>\r\n"
			+ "                <!-- email copyright end -->\r\n"
			+ "              </td>\r\n"
			+ "            </tr>\r\n"
			+ "          </tbody>\r\n"
			+ "        </table>\r\n"
			+ "      </div>\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "</body>\r\n"
			+ "</html>";
}

}
